name: Setup size reports
description: Setup size reports
inputs:
  gh-context:
    description: "GH Context"
    required: true

runs:
  using: "composite"
  steps:
  - uses: Wandalen/wretry.action@v1.4.10
    name: Set up environment for size reports
    env:
      GH_CONTEXT: ${{ inputs.gh-context }}
    with:
      command: scripts/memory/gh_sizes_environment.py "${GH_CONTEXT}"
      attempt_limit: 2
      attempt_delay: 2000
